name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você deseja monitorar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (caso seu app seja Node.js, altere conforme necessário)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules (opcional, para otimizar)
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Log in to Heroku
        uses: akshnz/heroku-login-action@v1
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - run: git push heroku main  # Se sua branch for diferente, altere "main" para o nome da branch correta

